## 1. Load an image and print its NumPy array shape

In [2]:
from PIL import Image
import numpy as np

# Load the sample image
image = Image.open("cricketer.jfif")

# Convert image to a NumPy array
image_array = np.array(image)

# Print image information
print("Image shape:", image_array.shape)
print("Image data type:", image_array.dtype)

Image shape: (148, 237, 3)
Image data type: uint8


## 2. Implement a simple 2D convolution using NumPy

In [3]:
import numpy as np

# 5x5 grayscale image
image = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

# 3x3 filter
filter_kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
])

# Output size: (5-3+1) x (5-3+1) = 3x3
output = np.zeros((3, 3))

# Slide the filter over the image
for i in range(output.shape[0]):
    for j in range(output.shape[1]):

        # Extract the current 3x3 region
        region = image[i:i+3, j:j+3]

        # Element-wise multiplication and summation
        output[i, j] = np.sum(region * filter_kernel)

print("Feature Map:")
print(output)

Feature Map:
[[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]


## 3. Basic CNN architecture diagram

## 4. Implement 2×2 max pooling using NumPy

In [4]:
import numpy as np

def max_pooling(image):
    """
    Performs 2x2 max pooling with stride 2.
    """
    rows, cols = image.shape

    # Output dimensions
    output_rows = rows // 2
    output_cols = cols // 2

    output = np.zeros((output_rows, output_cols))

    # Perform max pooling
    for i in range(output_rows):
        for j in range(output_cols):

            # Extract 2x2 neighborhood
            region = image[
                i*2:i*2+2,
                j*2:j*2+2
            ]

            # Store maximum value
            output[i, j] = np.max(region)

    return output


# Example image
image = np.array([
    [1, 3, 2, 4],
    [5, 6, 7, 8],
    [9, 2, 1, 3],
    [4, 5, 6, 7]
])

result = max_pooling(image)

print("Original image:")
print(image)

print("\nAfter 2x2 max pooling:")
print(result)

Original image:
[[1 3 2 4]
 [5 6 7 8]
 [9 2 1 3]
 [4 5 6 7]]

After 2x2 max pooling:
[[6. 8.]
 [9. 7.]]


## 5. Real-world example: Instagram/Zomato
On Instagram, a CNN used for image understanding can learn facial features and recognize a face even when the face appears in a different position within a photo. Similarly, Zomato can use image-recognition techniques to identify food-related visual features even when a dish is placed at different positions or scales in a photograph. This ability is related to translation invariance, where learned features can remain useful when their location in the image changes.